[versions]
paper-api = "1.21-R0.1-SNAPSHOT"
lombok = "1.18.34"
shadow = "8.1.8"
run-paper = "2.3.0"
nexo = "0.10.0-dev.0"
denizen = "1.3.0-SNAPSHOT"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
nexo = { group = "com.nexomc", name = "nexo", version.ref = "nexo"}
denizen = { group = "com.denizenscript", name = "denizen", version.ref = "denizen"  }

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
shadow = { id = "io.github.goooler.shadow", version.ref = "shadow" }